name: Deploy to Github Pages

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Setting git config
        env:
          USER_NAME: ${{ github.event.pull_request.assigned.name }}
          USER_EMAIL: ${{ github.event.pull_request.assigned.email }}
        run:
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"

      - name: Deploy to Github Pages
        if: github.event.pull_request.merged == true
        run: pnpm GHdeploy
