name: pull request test

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Setting git config
        run: |
          git config --global user.name "Yoon Jaehyun"
          git config --global user.email "yuchem2@gmail.com"

      - name: Deploy to Github Pages
        run: pnpm GHdeploy